// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxvNhwwOZLy4qVv0wiUluNwK23rwOiqvY',
    appId: '1:893288452883:web:a4ae0ae943df94abb6c0e6',
    messagingSenderId: '893288452883',
    projectId: 'traces-school-bus',
    authDomain: 'traces-school-bus.firebaseapp.com',
    storageBucket: 'traces-school-bus.firebasestorage.app',
    measurementId: 'G-QQ65TYKMBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe_I5ZLCCrA5Y6p2UF05qv9PQeaRwMpkE',
    appId: '1:893288452883:android:1d36b09b84d3f0bfb6c0e6',
    messagingSenderId: '893288452883',
    projectId: 'traces-school-bus',
    storageBucket: 'traces-school-bus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzi4ea9cMHxwk8-CIF7ANlcW-igQ76fwk',
    appId: '1:893288452883:ios:e3c5bb2d07ef0d39b6c0e6',
    messagingSenderId: '893288452883',
    projectId: 'traces-school-bus',
    storageBucket: 'traces-school-bus.firebasestorage.app',
    iosBundleId: 'com.example.tracesSchoolBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzi4ea9cMHxwk8-CIF7ANlcW-igQ76fwk',
    appId: '1:893288452883:ios:e3c5bb2d07ef0d39b6c0e6',
    messagingSenderId: '893288452883',
    projectId: 'traces-school-bus',
    storageBucket: 'traces-school-bus.firebasestorage.app',
    iosBundleId: 'com.example.tracesSchoolBus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxvNhwwOZLy4qVv0wiUluNwK23rwOiqvY',
    appId: '1:893288452883:web:f3f45acc15ba3a4cb6c0e6',
    messagingSenderId: '893288452883',
    projectId: 'traces-school-bus',
    authDomain: 'traces-school-bus.firebaseapp.com',
    storageBucket: 'traces-school-bus.firebasestorage.app',
    measurementId: 'G-ELQ58WE989',
  );
}
